env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - plugin:vue/essential
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  parser: '@typescript-eslint/parser'
plugins:
  - vue
  - '@typescript-eslint'
rules: {}
